### PR TITLE
LevelSetHDDA Improvements

### PR DESCRIPTION
**Pull request by danrbailey**

### CODE REVIEW

**Comment by MrMormon** [comment]
Why was this closed?

**Comment by caron** [comment]
`tools::LevelSetRayIntersector` uses `math::LevelSetHDDA` internally... the test was redundant?

**Comment by MrMormon** [comment]
Sorry, I was just researching what parts of OpenVDB need to be merged before I fork it for my own documentation purposes.

**Comment by danrbailey** [comment]
The confusion was that the ray-tracing in OpenVDB assumes vertex-centered rather than cell-centered transforms. This wasn't clear to me when I submitted this unit test.

I've suggested that ideally the ray-tracing should be able to handle both styles of transform, but as it stands this unit test isn't correct.

**Pull request closed without merging**
