### PR TITLE
Cmake updates + GR_PrimVDBPoints name collision fix

### PR DESCRIPTION
**Pull request by plattfot**
cmake updates:
- Added option to disable building the core libraries for openvdb (OPENVDB_BUILD_CORE). Useful if you want to build openvdb_houdini, openvdb_maya or pyopenvdb against an already built openvdb library.
- Moved the python modules to a separate cmake module. Allows you to disable it when building the core (OPENVDB_BUILD_PYTHON_MODULE).
- Added options in openvdb_houdini's CMakeLists.txt to match the output you get from using the openvdb_houdini's Makefile. 
- Removed unnecessary link dependencies for the core library.
- Renamed the variable OPENVDB_BUILD_VERSION_NUMBER to OPENVDB_PATCH_VERSION_NUMBER, since it's containing the patch number not a build number.

GR_PrimVDBPoints fix:
- Added DWA to the name when register the rendering hook and lowered the priority. This to avoid colliding with the openvdb plugins shipped with houdini.

### CODE REVIEW

**Comment by danrbailey** [comment]
Thanks for this @plattfot! I hope it's ok, I've split out the GR primitive hook change into a new PR because it's probably a little easier for the @OpenVDB-DevTeam to review and merge in isolation:

https://github.com/dreamworksanimation/openvdb/pull/148

I'd suggest it's probably best if @nyue reviews your CMake changes.

**Comment by plattfot** [comment]
No problem @danrbailey, thanks for splitting it up.

**Comment by nyue** [comment]
Thank you @plattfot for contributing to the CMake build. 

I have reviewed the CMake changes.

The conditional build of OpenVDB core and to separation of the Python module build are very useful.

I noticed that some of the changes committed are indentation lump with actual changes to CMake configuration files.

As Travis is not building with CMake and I don't have access to the fork with those CMake changes, I can verify the build.

Cheers

**Comment by plattfot** [comment]
Yeah, had to do some changes to make it behave similar to the Makefiles. The default for the cmake build should be the same as before.

You should be able to just clone that branch on our fork i.e.
git clone -b cmake-updates --single-branch https://github.com/digitaldomain/openvdb.git
and test it out.

Also I noticed that I missed to remove an old file that we used when we were using our build system + openvdb's Makefiles (openvdb/maya.mk). I just removed that one.

**Comment by nyue** [comment]
Thanks @plattfot , I have successfully build (using CMake) from Digital Domain's fork  with H16 on CentOS 7 and loaded one of the DWA OpenVDB Houdini node to verify it works.

**Comment by OpenVDB-DevTeam** [comment]
@nyue, would you mind to take a look at pull requests #119 and #123 as well?

**Comment by nyue** [comment]
Yes, I will have a look at pull requests #119 and #123

**Comment by OpenVDB-DevTeam** [comment]
Thanks!

**Pull request merged**
